### ISSUE TITLE
./jig arucostart Go woes

### ISSUE THREAD

**Issue by ppkn** [jhaip/programmable-space#6]
Error output:
```
$ ./jig arucostart
running broker
done sleeping
done running 1
couldn't open sink "/Users/daniel.pipkin/programmable-space/broker/broker.log": open /Users/daniel.pipkin/programmable-space/broker/broker.log: no such file or directory
exit status 1
done sleeping 2
booting
$ 1382__print-paper.go:16:2: missing go.sum entry for module providing package github.com/jung-kurt/gofpdf; to add:
        go mod download github.com/jung-kurt/gofpdf
```

If I then install gofpdf and run it again

```
$ ./jig arucostart
running broker
done sleeping
done running 1
couldn't open sink "/Users/daniel.pipkin/programmable-space/broker/broker.log": open /Users/daniel.pipkin/programmable-space/broker/broker.log: no such file or directory
exit status 1
done sleeping 2
booting
$ 2021/09/26 16:50:39 error opening file: open /Users/daniel.pipkin/programmable-space/src/programs/logs/1382__print-paper.log: no such file or directory
exit status 1
```

I'm running on MacOS Big Sur and made some modifications to `package.json` and `jig` to get it to run.

I've also tried `touch src/programs/logs/1382__print-paper.log` but that hasn't helped.

**Comment by ppkn** [comment]
I just realized that I have this in a folder deeper than `/Users/daniel.pipkin/`. I'll move it to my home folder today and see if I can get it to work.

**Comment by ppkn** [comment]
Well now everything is fine...?
```console
~/programmable-space (master) $ ./jig arucostart
running broker
done sleeping
done running 1
done sleeping 2
booting
```
But I can't seem to get anything at `localhost:3000`.

**Comment by jhaip** [comment]
Thanks for reporting this @ppkn ! There are lots of hardcoded paths from my linux servers that I'll need to clean up.

I just pushed bfb4db3 which removes the hardcoded node path from `./jig arucostart` and the removes the requirement for the broker to be run from the home directory.

I just tested `./jig arucostart` on macOS Big Sur and was able to get the basic programs running is a non-home folder with these changes.

Useful debugging things that I should document more:
* `./jig log` to tail the `broker.log` file and see what programs are connecting/pinging the broker, what programs the broker is sending and receiving messages from
* `ps aux | grep programs/` to see what programmable space programs are running on your host computer
    * `node src/programs/1900__processManager.js` is the program that manages starting all of the other programs so check if that one is running.
    * The `localhost:3000` debug view comes from program 10 so check if that program is running `ps aux | grep 10__debugViewer.js`
    * I would also check if program 112 is running `ps aux | grep 112__arucoEditorBoot.js` because that is the program that wishes all the boot programs would be running. Program 1900 then should hear about these wishes and run the programs on your host computer.
* Each program should be logging to a file `src/programs/logs` folder. For example, to see the logs of program 1900 I would `tail -f src/programs/logs/1900__processManager.log`. This is useful for print debugging and finding errors from program crashes.

I haven't spent much time exposing issues with programs starting or dying unexpectedly so this is a known rough spot. If I suspect things are going wrong, I always double check if the program's process if running, tail the program logs, check the broker logs, and sometimes run the program by hand from the command line.

**Comment by ppkn** [comment]
`./jig log` isn't getting any further than `listening...`.

`ps aux | grep programs/` shows running processes (even some duplicates, which is weird because I made sure to kill everything before running ./jig arucostart again).
```
daniel.pipkin    35147   0.3  0.1  4659124  17108 s002  S     8:11PM   3:33.83 node src/programs/577__programEditor.js
daniel.pipkin    35144   0.3  0.1  4659124  16000 s002  S     8:11PM   3:31.65 node src/programs/826__runSeenPapers.js
daniel.pipkin    35143   0.3  0.3  4679116  43128 s002  S     8:11PM   5:55.21 node src/programs/20__httpClient.js
daniel.pipkin    35099   0.3  0.1  4659636  15684 s002  S     8:11PM   3:34.49 node src/programs/112__arucoEditorBoot.js
daniel.pipkin    35165   0.3  0.1  4659380  17440 s002  S     8:12PM   3:32.68 node src/programs/1900__processManager.js
daniel.pipkin    35152   0.3  0.2  4673624  41348 s002  S     8:11PM   4:48.62 node src/programs/10__debugViewer.js
daniel.pipkin    35151   0.3  0.1  4668396  24876 s002  S     8:11PM   3:31.29 node src/programs/1636__arucoWebManager.js
daniel.pipkin    35148   0.3  0.1  4659380  17100 s002  S     8:11PM   3:32.12 node src/programs/112__arucoEditorBoot.js
daniel.pipkin    35145   0.3  0.1  4661948  21428 s002  S     8:11PM   3:33.87 node src/programs/11__latencyMonitor.js
daniel.pipkin    35149   0.2  0.1  4659124  17604 s002  S     8:11PM   3:34.94 node src/programs/40__parser.js
daniel.pipkin    35130   0.2  0.1  4661948  17104 s002  S     8:11PM   3:32.38 node src/programs/1900__processManager.js
daniel.pipkin    35150   0.1  0.1  4659388  18364 s002  S     8:11PM   3:35.03 node src/programs/1459__createNewPaper.js
```
There are some logs that are getting written to, but not all of them (e.g. `processManager` isn't writing any logs).

localhost:5000 just has a red page that says "error parsing"  
There is one fact in the broker's fact table. It's just 0 with the current timestamp.  
The arucoWebManager seems to be running great 😄 

I don't have a lot of time to dig into it but right now it seems like there is something broken with my broker. I don't see it listening on 5570.

**Comment by jhaip** [comment]
Hmm I haven't seen the
```
interrupted system call
exit status 1
```
issue before. It seems to be related to the Golang ZeroMQ library that the broker is using. ([ZeroMQ library issue](https://github.com/pebbe/zmq4/issues/17), [Golang bug report](https://github.com/golang/go/issues/36281)).

There was some mention there that this could be an issue related to the Golang version (specifically 1.14). On my linux server I am using `go1.13.7 linux/amd64` and on my BigSur MacOS I am using `go1.14.4 darwin/amd64`. [Some links](https://github.com/golang/go/blob/2d6f8cc2cdd5993eb8dc80655735a38ef067af6e/doc/go1.14.html#L270) are seem to say that retrying is the correct behavior and [I think the broker is currently doing that](https://github.com/jhaip/programmable-space/blob/master/broker/broker.go#L434) but maybe it's a different part of the broker code that is erroring.

@ppkn What does `go version` say for you?

**Comment by ppkn** [comment]
```
~/p/programmable-space (master) $ go version
go version go1.17.1 darwin/amd64
```

**Comment by ppkn** [comment]
I'm pretty sure I've got Go in a stable place now so I'm going to go ahead and close this issue.
(I think I had too many Go processes running in the background with all of my retrying `./jig arucostart`)
